name: staffprofiles
author: mcmdev
version: ${version}
api-version: 1.21
description: Lets staff members disguise themselves as a different game profile using the /sprofile command.
website: https://github.com/MCMDEV/staffprofiles
main: de.mcmdev.staffprofiles.StaffprofilesPaper
folia-supported: true